# Generated by Django 5.2.5 on 2025-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=15, unique=True)),
                ('pharmacy', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=15)),
                ('type_access', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('item_quantity', models.IntegerField()),
                ('sync_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
